-- ============================================
-- POPULATE COMPANIES AND COURSES TABLES
-- Run this script in Supabase SQL Editor
-- ============================================

-- First, clear existing data (optional - uncomment if needed)
-- TRUNCATE TABLE public.courses CASCADE;
-- TRUNCATE TABLE public.companies CASCADE;

-- ============================================
-- INSERT COMPANIES
-- ============================================

INSERT INTO public.companies (name, industry, location, description, contact_info, website, employee_count, founded) VALUES
('Siemens', 'Industrial Automation', 'Mumbai, India', 'Global leader in industrial automation, digitalization, and electrification solutions.', '+91 22 3967 0000', 'https://siemens.com', 50000, '1847'),
('ABB', 'Power & Automation', 'Bangalore, India', 'Pioneering technology leader in electrification, robotics, and industrial automation.', '+91 80 2294 9100', 'https://abb.com', 45000, '1883'),
('Rockwell Automation', 'Industrial Automation', 'Pune, India', 'World''s largest company dedicated to industrial automation and information solutions.', '+91 20 6601 1000', 'https://rockwellautomation.com', 25000, '1903'),
('Emerson', 'Process Management', 'Delhi, India', 'Global technology and engineering company providing innovative solutions for customers.', '+91 11 4666 6000', 'https://emerson.com', 35000, '1890'),
('Schneider Electric', 'Energy Management', 'Hyderabad, India', 'Global specialist in energy management and automation solutions.', '+91 40 6677 7000', 'https://schneider-electric.com', 40000, '1836'),
('Honeywell', 'Industrial Solutions', 'Chennai, India', 'Fortune 100 company that invents and manufactures technologies to address critical challenges.', '+91 44 6656 1000', 'https://honeywell.com', 30000, '1906'),
('Yokogawa', 'Industrial Automation', 'Mumbai, India', 'Leading provider of industrial automation and test and measurement solutions.', '+91 22 2493 4000', 'https://yokogawa.com', 15000, '1915'),
('FANUC', 'Robotics & Automation', 'Bangalore, India', 'World leader in factory automation, robotics, and CNC systems.', '+91 80 2294 9200', 'https://fanuc.com', 8000, '1956'),
('Bosch', 'Technology & Services', 'Pune, India', 'Leading global supplier of technology and services in mobility, industrial technology, and consumer goods.', '+91 20 6601 2000', 'https://bosch.com', 35000, '1886'),
('Danfoss', 'Power Solutions', 'Ahmedabad, India', 'Global leader in engineering solutions for climate and energy efficiency.', '+91 79 6601 3000', 'https://danfoss.com', 12000, '1933'),
('Cisco', 'Networking & Security', 'Kolkata, India', 'Worldwide leader in IT and networking that helps companies seize the opportunities of tomorrow.', '+91 33 6601 4000', 'https://cisco.com', 25000, '1984'),
('SAP', 'Enterprise Software', 'Bangalore, India', 'Global leader in enterprise application software, helping companies run better.', '+91 80 2294 9300', 'https://sap.com', 20000, '1972'),
('Microsoft', 'Technology & Cloud', 'Hyderabad, India', 'Leading global technology company providing cloud computing, software, and hardware solutions.', '+91 40 6677 8000', 'https://microsoft.com', 45000, '1975'),
('Google Cloud', 'Cloud Computing', 'Mumbai, India', 'Leading cloud platform providing infrastructure, platform, and software services.', '+91 22 2493 5000', 'https://cloud.google.com', 15000, '2008'),
('Fortinet', 'Cybersecurity', 'Delhi, India', 'Global leader in broad, integrated, and automated cybersecurity solutions.', '+91 11 4666 7000', 'https://fortinet.com', 8000, '2000'),
('TATA Consultancy Services', 'IT Services', 'Mumbai, India', 'Leading global IT services, consulting, and business solutions organization.', '+91 22 3967 1000', 'https://tcs.com', 500000, '1968'),
('Infosys', 'IT Services', 'Bangalore, India', 'Global leader in next-generation digital services and consulting.', '+91 80 2294 9400', 'https://infosys.com', 350000, '1981'),
('Wipro', 'IT Services', 'Bangalore, India', 'Leading global information technology, consulting, and business process services company.', '+91 80 2294 9500', 'https://wipro.com', 250000, '1945'),
('L&T', 'Engineering & Construction', 'Mumbai, India', 'Leading Indian multinational engaged in technology, engineering, construction, manufacturing and financial services.', '+91 22 6752 5656', 'https://larsentoubro.com', 150000, '1938'),
('Suzlon', 'Renewable Energy', 'Pune, India', 'Global renewable energy solutions provider specializing in wind energy and sustainable power generation.', '+91 20 6702 5000', 'https://suzlon.com', 8000, '1995'),
('BHEL', 'Power Generation', 'Delhi, India', 'India''s largest engineering and manufacturing company in the energy-related infrastructure sector.', '+91 11 2340 3000', 'https://bhel.com', 45000, '1964'),
('TATA Motors', 'Automotive', 'Mumbai, India', 'Leading global automobile manufacturer with a portfolio of cars, utility vehicles, trucks, buses and defense vehicles.', '+91 22 2498 1444', 'https://tatamotors.com', 80000, '1945'),
('Mahindra & Mahindra', 'Automotive', 'Mumbai, India', 'Leading Indian multinational automotive manufacturing corporation with diversified business interests.', '+91 22 2490 1441', 'https://mahindra.com', 75000, '1945'),
('Maruti Suzuki', 'Automotive', 'Delhi, India', 'India''s largest passenger vehicle manufacturer, a subsidiary of Japanese car and motorcycle manufacturer Suzuki.', '+91 11 4678 1000', 'https://marutisuzuki.com', 40000, '1981'),
('Ashok Leyland', 'Automotive', 'Chennai, India', 'Indian multinational automotive manufacturer, the second largest commercial vehicle manufacturer in India.', '+91 44 4599 9999', 'https://ashokleyland.com', 15000, '1948')
ON CONFLICT DO NOTHING;

-- ============================================
-- INSERT COURSES
-- ============================================

INSERT INTO public.courses (
  title, company_id, company_name, location, type, duration, price, image_url, description, 
  tags, contact, website, rating, student_count, is_active
) VALUES
(
  'PLC Programming & Automation',
  (SELECT id FROM public.companies WHERE name = 'Siemens' LIMIT 1),
  'Siemens',
  'Mumbai, India',
  'Industrial Training',
  '6 weeks',
  '₹45,000',
  'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.1.0',
  'Comprehensive PLC programming training covering Siemens S7-1200 and TIA Portal software with hands-on automation projects.',
  ARRAY['PLC', 'Automation', 'Siemens', 'Industrial'],
  '+91 98765 43210',
  'https://siemens.com',
  4.8,
  245,
  true
),
(
  'Electrical Panel Design',
  (SELECT id FROM public.companies WHERE name = 'ABB' LIMIT 1),
  'ABB',
  'Bangalore, India',
  'Technical Training',
  '4 weeks',
  '₹35,000',
  'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?q=80&w=2669&auto=format&fit=crop&ixlib=rb-4.1.0',
  'Learn electrical panel design principles, component selection, and safety standards for industrial applications.',
  ARRAY['Electrical', 'Panel Design', 'ABB', 'Industrial'],
  '+91 98765 43211',
  'https://abb.com',
  4.7,
  189,
  true
),
(
  'SCADA System Development',
  (SELECT id FROM public.companies WHERE name = 'Rockwell Automation' LIMIT 1),
  'Rockwell Automation',
  'Pune, India',
  'Software Training',
  '5 weeks',
  '₹40,000',
  'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.1.0',
  'Master SCADA system development using FactoryTalk View Studio with real-world industrial applications.',
  ARRAY['SCADA', 'Rockwell', 'HMI', 'Automation'],
  '+91 98765 43212',
  'https://rockwellautomation.com',
  4.6,
  156,
  true
),
(
  'Industrial Robotics Programming',
  (SELECT id FROM public.companies WHERE name = 'FANUC' LIMIT 1),
  'FANUC',
  'Chennai, India',
  'Robotics Training',
  '8 weeks',
  '₹55,000',
  'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.1.0',
  'Comprehensive robotics programming training covering FANUC robots, teach pendant operation, and automation integration.',
  ARRAY['Robotics', 'FANUC', 'Automation', 'Programming'],
  '+91 98765 43213',
  'https://fanuc.com',
  4.9,
  134,
  true
),
(
  'Process Control & Instrumentation',
  (SELECT id FROM public.companies WHERE name = 'Emerson' LIMIT 1),
  'Emerson',
  'Delhi, India',
  'Process Training',
  '6 weeks',
  '₹42,000',
  'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.1.0',
  'Learn process control systems, instrumentation, and DeltaV DCS programming for industrial processes.',
  ARRAY['Process Control', 'Instrumentation', 'Emerson', 'DCS'],
  '+91 98765 43214',
  'https://emerson.com',
  4.5,
  178,
  true
),
(
  'HMI Development & Design',
  (SELECT id FROM public.companies WHERE name = 'Schneider Electric' LIMIT 1),
  'Schneider Electric',
  'Hyderabad, India',
  'Software Training',
  '4 weeks',
  '₹38,000',
  'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.1.0',
  'Master HMI development using Vijeo Designer and Wonderware InTouch for industrial automation applications.',
  ARRAY['HMI', 'Schneider', 'Design', 'Automation'],
  '+91 98765 43215',
  'https://schneider-electric.com',
  4.7,
  167,
  true
),
(
  'Industrial Networking & Communication',
  (SELECT id FROM public.companies WHERE name = 'Cisco' LIMIT 1),
  'Cisco',
  'Kolkata, India',
  'Network Training',
  '5 weeks',
  '₹36,000',
  'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.1.0',
  'Learn industrial networking protocols, Ethernet/IP, Profinet, and network security for automation systems.',
  ARRAY['Networking', 'Cisco', 'Industrial', 'Communication'],
  '+91 98765 43216',
  'https://cisco.com',
  4.4,
  145,
  true
),
(
  'Variable Frequency Drive Programming',
  (SELECT id FROM public.companies WHERE name = 'Danfoss' LIMIT 1),
  'Danfoss',
  'Ahmedabad, India',
  'Drive Training',
  '3 weeks',
  '₹28,000',
  'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?q=80&w=2669&auto=format&fit=crop&ixlib=rb-4.1.0',
  'Comprehensive VFD programming training covering parameter setting, commissioning, and troubleshooting.',
  ARRAY['VFD', 'Danfoss', 'Drives', 'Programming'],
  '+91 98765 43217',
  'https://danfoss.com',
  4.6,
  123,
  true
),
(
  'Safety Systems & SIL Training',
  (SELECT id FROM public.companies WHERE name = 'Honeywell' LIMIT 1),
  'Honeywell',
  'Mumbai, India',
  'Safety Training',
  '4 weeks',
  '₹45,000',
  'https://images.unsplash.com/photo-1563013544-824ae1b704d3?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.1.0',
  'Learn safety instrumented systems, SIL calculations, and Safety Manager programming for critical applications.',
  ARRAY['Safety', 'Honeywell', 'SIL', 'Critical Systems'],
  '+91 98765 43218',
  'https://honeywell.com',
  4.8,
  98,
  true
),
(
  'Industrial IoT & Industry 4.0',
  (SELECT id FROM public.companies WHERE name = 'Bosch' LIMIT 1),
  'Bosch',
  'Bangalore, India',
  'IoT Training',
  '6 weeks',
  '₹48,000',
  'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.1.0',
  'Master Industrial IoT concepts, data analytics, and Industry 4.0 implementation strategies.',
  ARRAY['IoT', 'Industry 4.0', 'Bosch', 'Analytics'],
  '+91 98765 43219',
  'https://bosch.com',
  4.7,
  167,
  true
),
(
  'Motor Control & Protection',
  (SELECT id FROM public.companies WHERE name = 'Siemens' LIMIT 1),
  'Siemens',
  'Pune, India',
  'Motor Training',
  '4 weeks',
  '₹32,000',
  'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?q=80&w=2669&auto=format&fit=crop&ixlib=rb-4.1.0',
  'Learn motor control systems, protection relays, and soft starter programming for industrial applications.',
  ARRAY['Motor Control', 'Siemens', 'Protection', 'Industrial'],
  '+91 98765 43220',
  'https://siemens.com',
  4.5,
  134,
  true
),
(
  'DCS Programming & Configuration',
  (SELECT id FROM public.companies WHERE name = 'Yokogawa' LIMIT 1),
  'Yokogawa',
  'Chennai, India',
  'DCS Training',
  '7 weeks',
  '₹52,000',
  'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.1.0',
  'Master DCS programming using CENTUM VP with advanced control strategies and system integration.',
  ARRAY['DCS', 'Yokogawa', 'CENTUM', 'Control Systems'],
  '+91 98765 43221',
  'https://yokogawa.com',
  4.9,
  89,
  true
),
(
  'Industrial Cybersecurity',
  (SELECT id FROM public.companies WHERE name = 'Fortinet' LIMIT 1),
  'Fortinet',
  'Delhi, India',
  'Security Training',
  '5 weeks',
  '₹40,000',
  'https://images.unsplash.com/photo-1563013544-824ae1b704d3?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.1.0',
  'Learn industrial cybersecurity, network protection, and security best practices for automation systems.',
  ARRAY['Cybersecurity', 'Fortinet', 'Security', 'Industrial'],
  '+91 98765 43222',
  'https://fortinet.com',
  4.6,
  112,
  true
),
(
  'Batch Process Control',
  (SELECT id FROM public.companies WHERE name = 'Emerson' LIMIT 1),
  'Emerson',
  'Mumbai, India',
  'Process Training',
  '6 weeks',
  '₹46,000',
  'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.1.0',
  'Master batch process control using DeltaV Batch with recipe management and batch execution strategies.',
  ARRAY['Batch Control', 'Emerson', 'Process', 'DeltaV'],
  '+91 98765 43223',
  'https://emerson.com',
  4.7,
  78,
  true
),
(
  'Industrial Data Analytics',
  (SELECT id FROM public.companies WHERE name = 'SAP' LIMIT 1),
  'SAP',
  'Bangalore, India',
  'Analytics Training',
  '8 weeks',
  '₹58,000',
  'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.1.0',
  'Learn industrial data analytics, predictive maintenance, and performance optimization using SAP solutions.',
  ARRAY['Analytics', 'SAP', 'Predictive', 'Data Science'],
  '+91 98765 43224',
  'https://sap.com',
  4.8,
  145,
  true
),
(
  'Motion Control Systems',
  (SELECT id FROM public.companies WHERE name = 'Rockwell Automation' LIMIT 1),
  'Rockwell Automation',
  'Pune, India',
  'Motion Training',
  '5 weeks',
  '₹44,000',
  'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.1.0',
  'Master motion control systems using Kinetix drives and servo programming for precision applications.',
  ARRAY['Motion Control', 'Rockwell', 'Servo', 'Precision'],
  '+91 98765 43225',
  'https://rockwellautomation.com',
  4.9,
  67,
  true
),
(
  'Industrial Wireless Communication',
  (SELECT id FROM public.companies WHERE name = 'Honeywell' LIMIT 1),
  'Honeywell',
  'Chennai, India',
  'Wireless Training',
  '4 weeks',
  '₹35,000',
  'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.1.0',
  'Learn industrial wireless communication protocols, mesh networks, and wireless sensor networks.',
  ARRAY['Wireless', 'Honeywell', 'Communication', 'Sensors'],
  '+91 98765 43226',
  'https://honeywell.com',
  4.5,
  89,
  true
),
(
  'Advanced Process Control',
  (SELECT id FROM public.companies WHERE name = 'ABB' LIMIT 1),
  'ABB',
  'Mumbai, India',
  'Advanced Training',
  '8 weeks',
  '₹65,000',
  'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.1.0',
  'Master advanced process control techniques, model predictive control, and optimization strategies.',
  ARRAY['Advanced Control', 'ABB', 'MPC', 'Optimization'],
  '+91 98765 43227',
  'https://abb.com',
  4.9,
  56,
  true
),
(
  'Industrial Cloud Solutions',
  (SELECT id FROM public.companies WHERE name = 'Microsoft' LIMIT 1),
  'Microsoft',
  'Bangalore, India',
  'Cloud Training',
  '6 weeks',
  '₹42,000',
  'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.1.0',
  'Learn Azure IoT Hub, industrial cloud platforms, and digital twin implementation for Industry 4.0.',
  ARRAY['Cloud', 'Microsoft', 'Azure', 'Digital Twin'],
  '+91 98765 43228',
  'https://microsoft.com',
  4.6,
  123,
  true
),
(
  'Industrial Machine Learning',
  (SELECT id FROM public.companies WHERE name = 'Google Cloud' LIMIT 1),
  'Google Cloud',
  'Delhi, India',
  'AI Training',
  '10 weeks',
  '₹72,000',
  'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.1.0',
  'Master industrial machine learning, predictive analytics, and AI implementation for automation systems.',
  ARRAY['Machine Learning', 'Google', 'AI', 'Predictive'],
  '+91 98765 43229',
  'https://cloud.google.com',
  4.8,
  78,
  true
),
(
  'Power Systems & Distribution',
  (SELECT id FROM public.companies WHERE name = 'L&T' LIMIT 1),
  'L&T',
  'Mumbai, India',
  'Power Training',
  '7 weeks',
  '₹50,000',
  'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?q=80&w=2669&auto=format&fit=crop&ixlib=rb-4.1.0',
  'Comprehensive power systems training covering distribution networks, protection systems, and grid management.',
  ARRAY['Power Systems', 'L&T', 'Distribution', 'Grid'],
  '+91 98765 43230',
  'https://larsentoubro.com',
  4.7,
  156,
  true
),
(
  'Renewable Energy Systems',
  (SELECT id FROM public.companies WHERE name = 'Suzlon' LIMIT 1),
  'Suzlon',
  'Pune, India',
  'Renewable Training',
  '6 weeks',
  '₹45,000',
  'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.1.0',
  'Learn renewable energy systems, solar power, wind energy, and sustainable energy management.',
  ARRAY['Renewable Energy', 'Suzlon', 'Solar', 'Wind'],
  '+91 98765 43231',
  'https://suzlon.com',
  4.6,
  134,
  true
),
(
  'Smart Grid Technologies',
  (SELECT id FROM public.companies WHERE name = 'BHEL' LIMIT 1),
  'BHEL',
  'Delhi, India',
  'Grid Training',
  '8 weeks',
  '₹55,000',
  'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.1.0',
  'Master smart grid technologies, IoT integration, and advanced metering infrastructure.',
  ARRAY['Smart Grid', 'BHEL', 'IoT', 'Metering'],
  '+91 98765 43232',
  'https://bhel.com',
  4.8,
  98,
  true
),
(
  'Energy Management Systems',
  (SELECT id FROM public.companies WHERE name = 'Schneider Electric' LIMIT 1),
  'Schneider Electric',
  'Bangalore, India',
  'Energy Training',
  '5 weeks',
  '₹42,000',
  'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.1.0',
  'Learn energy management systems, efficiency optimization, and sustainability practices.',
  ARRAY['Energy Management', 'Schneider', 'Efficiency', 'Sustainability'],
  '+91 98765 43233',
  'https://schneider-electric.com',
  4.7,
  167,
  true
),
(
  'Industrial Automation & Control',
  (SELECT id FROM public.companies WHERE name = 'TATA Motors' LIMIT 1),
  'TATA Motors',
  'Mumbai, India',
  'Automation Training',
  '9 weeks',
  '₹60,000',
  'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.1.0',
  'Comprehensive industrial automation training covering manufacturing processes and control systems.',
  ARRAY['Automation', 'TATA Motors', 'Manufacturing', 'Control'],
  '+91 98765 43234',
  'https://tatamotors.com',
  4.9,
  145,
  true
);

-- ============================================
-- VERIFY DATA
-- ============================================

-- Check company count
SELECT COUNT(*) as company_count FROM public.companies;

-- Check course count
SELECT COUNT(*) as course_count FROM public.courses;

-- View sample companies
SELECT id, name, industry, location FROM public.companies LIMIT 5;

-- View sample courses
SELECT id, title, company_name, location, rating, student_count FROM public.courses LIMIT 5;

